{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yifeiyuan.flap",
    "module": "plugin",
    "version": "1.1.0-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "d3nyahnum5gtre2b66fgt3llt4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.1.0-test.jar",
          "url": "plugin-1.1.0-test.jar",
          "size": 11406,
          "sha512": "7a494692f7401f2c4e58b82ab2889d3f0eacb2ec5d9f58ce05c07be0895e07876ac65555bcfaef10eef80fc973d1c00b3f1fe5473c2e6f071998b82a156371fd",
          "sha256": "d1f99a70899dfbf13a26dc2c311b978d72aac1906fecad779a2e0c3e7f500cfc",
          "sha1": "116dd7f4ee81d27ae5d3d207c8f0b25604127c36",
          "md5": "d6dd68365a90ef8a935367f0c4e30e3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.1.0-test.jar",
          "url": "plugin-1.1.0-test.jar",
          "size": 11406,
          "sha512": "7a494692f7401f2c4e58b82ab2889d3f0eacb2ec5d9f58ce05c07be0895e07876ac65555bcfaef10eef80fc973d1c00b3f1fe5473c2e6f071998b82a156371fd",
          "sha256": "d1f99a70899dfbf13a26dc2c311b978d72aac1906fecad779a2e0c3e7f500cfc",
          "sha1": "116dd7f4ee81d27ae5d3d207c8f0b25604127c36",
          "md5": "d6dd68365a90ef8a935367f0c4e30e3a"
        }
      ]
    }
  ]
}
